spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eventmanage
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create

    mail:
      host: smtp.gmail.com
      port: 587
      username: eventifysystem@gmail.com
      password: wxyvhayqbovlnamf
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true